#if __has_include ("\bwa3_eagle\data\bwa3_eagle_co.paa")
class CfgFunctions
{
	class rsr_bwa3
	{
		tag="RsR";
		class init
		{
			file="\rsr_vanilla\functions";
			class advancedTowingInit
			{
				postInit=1;
			};
			class remove_turret_weapons
			{
			};
			class fired
			{
			};
		};
	};
};
class CfgPatches
{
	class rsr_bwa3
	{
		requiredAddons[]=
		{
			"rsr_core"
		};
		units[]=
		{
			"rsr_eagle",
			"rsr_eagle_flecktarn_lowvis",
			"rsr_eagle_trop",
			"rsr_eagle_tropen_lowvis"
		};
		weapons[]={};
	};
};
class CfgVehicles
{
	class bwa3_eagle_fleck;
	class rsr_eagle: bwa3_eagle_fleck
	{
		author="RsR";
		displayName="Eagle San - Flecktarn";
		typicalCargo[]=
		{
			"B_Soldier_F"
		};
		side=1;
		crew="B_Soldier_F";
		editorPreview="";
		editorCategory="rsrVehicles";
		editorSubcategory="rsrCar";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		hiddenSelectionsTextures[]=
		{
			"\rsr_bwa3\data\eagle\bwa3_eagle_co",
			"\bwa3_eagle\data\bwa3_eagle_fahrwerk_co.paa",
			"\bwa3_eagle\data\bwa3_eagle_int_co.paa",
			"\bwa3_eagle\data\bwa3_eagle_alpha_co.paa",
			"#(argb,8,8,3)color(0.345098,0.345098,0.345098,1.0,co)",
			"\bwa3_eagle\data\bwa3_eagle_parts_co.paa",
			"\bwa3_backpacks\data\bwa3_backpack_fleck_co.paa",
			"\bwa3_backpacks\data\bwa3_backpack_fleck_co.paa",
			"\bwa3_common\data\bwa3_normteile_co.paa",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)"
		};
		hiddenSelections[]=
		{
			"chassie",
			"fahrwerk",
			"interior",
			"Glass",
			"mirror_glass",
			"parts",
			"backpack_back",
			"backpack_top",
			"licenseplate",
			"takt_a",
			"takt_b",
			"takt_c",
			"takt_d",
			"y_a",
			"y_b",
			"y_c",
			"y_d",
			"y_e",
			"y_f",
			"insignia"
		};
		class TextureSources
		{
			class eagle_flecktarn
			{
				displayName="Flecktarn";
				author="V1irus";
				textures[]=
				{
					"\rsr_bwa3\data\eagle\bwa3_eagle_co",
					"\bwa3_eagle\data\bwa3_eagle_fahrwerk_co.paa",
					"\bwa3_eagle\data\bwa3_eagle_int_co.paa",
					"\bwa3_eagle\data\bwa3_eagle_alpha_co.paa",
					"#(argb,8,8,3)color(0.345098,0.345098,0.345098,1.0,co)",
					"\bwa3_eagle\data\bwa3_eagle_parts_co.paa",
					"\bwa3_backpacks\data\bwa3_backpack_fleck_co.paa",
					"\bwa3_backpacks\data\bwa3_backpack_fleck_co.paa",
					"\bwa3_common\data\bwa3_normteile_co.paa",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)"
				};
				hiddenSelections[]=
				{
					"chassie",
					"fahrwerk",
					"interior",
					"Glass",
					"mirror_glass",
					"parts",
					"backpack_back",
					"backpack_top",
					"licenseplate",
					"takt_a",
					"takt_b",
					"takt_c",
					"takt_d",
					"y_a",
					"y_b",
					"y_c",
					"y_d",
					"y_e",
					"y_f",
					"insignia"
				};
				factions[]=
				{
					"BLU_F"
				};
			};
			class eagle_flecktarn_lowvis
			{
				displayName="Flecktarn lowvis";
				author="V1irus";
				textures[]=
				{
					"\rsr_bwa3\data\eagle\bwa3_eagle_co_vis",
					"\bwa3_eagle\data\bwa3_eagle_fahrwerk_co.paa",
					"\bwa3_eagle\data\bwa3_eagle_int_co.paa",
					"\bwa3_eagle\data\bwa3_eagle_alpha_co.paa",
					"#(argb,8,8,3)color(0.345098,0.345098,0.345098,1.0,co)",
					"\bwa3_eagle\data\bwa3_eagle_parts_co.paa",
					"\bwa3_backpacks\data\bwa3_backpack_fleck_co.paa",
					"\bwa3_backpacks\data\bwa3_backpack_fleck_co.paa",
					"\bwa3_common\data\bwa3_normteile_co.paa",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)"
				};
				hiddenSelections[]=
				{
					"chassie",
					"fahrwerk",
					"interior",
					"Glass",
					"mirror_glass",
					"parts",
					"backpack_back",
					"backpack_top",
					"licenseplate",
					"takt_a",
					"takt_b",
					"takt_c",
					"takt_d",
					"y_a",
					"y_b",
					"y_c",
					"y_d",
					"y_e",
					"y_f",
					"insignia"
				};
				factions[]=
				{
					"BLU_F"
				};
			};
		};
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=1;
			};
		};
		class TransportWeapons
		{
		};
		class TransportMagazines
		{
		};
	};
	class rsr_eagle_flecktarn_lowvis: rsr_eagle
	{
		author="RsR";
		displayName="Eagle San - Flecktarn lowvis";
		_generalMacro="I_MRAP_03_F";
		editorPreview="";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		hiddenSelectionsTextures[]=
		{
			"\rsr_bwa3\data\eagle\bwa3_eagle_co_vis",
			"\bwa3_eagle\data\bwa3_eagle_fahrwerk_co.paa",
			"\bwa3_eagle\data\bwa3_eagle_int_co.paa",
			"\bwa3_eagle\data\bwa3_eagle_alpha_co.paa",
			"#(argb,8,8,3)color(0.345098,0.345098,0.345098,1.0,co)",
			"\bwa3_eagle\data\bwa3_eagle_parts_co.paa",
			"\bwa3_backpacks\data\bwa3_backpack_fleck_co.paa",
			"\bwa3_backpacks\data\bwa3_backpack_fleck_co.paa",
			"\bwa3_common\data\bwa3_normteile_co.paa",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)"
		};
	};
	class bwa3_eagle_tropen;
	class rsr_eagle_trop: bwa3_eagle_tropen
	{
		author="RsR";
		displayName="Eagle San - Tropen";
		typicalCargo[]=
		{
			"B_Soldier_F"
		};
		side=1;
		crew="B_Soldier_F";
		editorPreview="";
		editorCategory="rsrVehicles";
		editorSubcategory="rsrCar";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		hiddenSelectionsTextures[]=
		{
			"\rsr_bwa3\data\eagle\bwa3_eagle_tropen_co",
			"\bwa3_eagle\data\bwa3_eagle_fahrwerk_co.paa",
			"\bwa3_eagle\data\bwa3_eagle_int_co.paa",
			"\bwa3_eagle\data\bwa3_eagle_alpha_co.paa",
			"#(argb,8,8,3)color(0.345098,0.345098,0.345098,1.0,co)",
			"\bwa3_eagle\data\bwa3_eagle_parts_co.paa",
			"\bwa3_backpacks\data\bwa3_backpack_fleck_co.paa",
			"\bwa3_backpacks\data\bwa3_backpack_fleck_co.paa",
			"\bwa3_common\data\bwa3_normteile_co.paa",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)"
		};
		class TextureSources
		{
			class eagle_tropentarn
			{
				displayName="Tropentarn";
				author="V1irus";
				textures[]=
				{
					"\rsr_bwa3\data\eagle\bwa3_eagle_tropen_co",
					"\bwa3_eagle\data\bwa3_eagle_fahrwerk_co.paa",
					"\bwa3_eagle\data\bwa3_eagle_int_co.paa",
					"\bwa3_eagle\data\bwa3_eagle_alpha_co.paa",
					"#(argb,8,8,3)color(0.345098,0.345098,0.345098,1.0,co)",
					"\bwa3_eagle\data\bwa3_eagle_parts_co.paa",
					"\bwa3_backpacks\data\bwa3_backpack_fleck_co.paa",
					"\bwa3_backpacks\data\bwa3_backpack_fleck_co.paa",
					"\bwa3_common\data\bwa3_normteile_co.paa",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)"
				};
				factions[]=
				{
					"BLU_F"
				};
			};
			class eagle_tropentarn_lowvis
			{
				displayName="Tropentarn lowvis";
				author="V1irus";
				textures[]=
				{
					"\rsr_bwa3\data\eagle\bwa3_eagle_tropen_co_vis",
					"\bwa3_eagle\data\bwa3_eagle_fahrwerk_co.paa",
					"\bwa3_eagle\data\bwa3_eagle_int_co.paa",
					"\bwa3_eagle\data\bwa3_eagle_alpha_co.paa",
					"#(argb,8,8,3)color(0.345098,0.345098,0.345098,1.0,co)",
					"\bwa3_eagle\data\bwa3_eagle_parts_co.paa",
					"\bwa3_backpacks\data\bwa3_backpack_fleck_co.paa",
					"\bwa3_backpacks\data\bwa3_backpack_fleck_co.paa",
					"\bwa3_common\data\bwa3_normteile_co.paa",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)"
				};
				factions[]=
				{
					"BLU_F"
				};
			};
		};
		class TransportItems
		{
			class _xx_FirstAidKit
			{
				name="FirstAidKit";
				count=1;
			};
		};
		class TransportWeapons
		{
		};
		class TransportMagazines
		{
		};
	};
	class rsr_eagle_tropen_lowvis: rsr_eagle_trop
	{
		author="RsR";
		displayName="Eagle San - Tropen lowvis";
		_generalMacro="I_MRAP_03_F";
		editorPreview="";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		hiddenSelectionsTextures[]=
		{
			"\rsr_bwa3\data\eagle\bwa3_eagle_tropen_co_vis",
			"\bwa3_eagle\data\bwa3_eagle_fahrwerk_co.paa",
			"\bwa3_eagle\data\bwa3_eagle_int_co.paa",
			"\bwa3_eagle\data\bwa3_eagle_alpha_co.paa",
			"#(argb,8,8,3)color(0.345098,0.345098,0.345098,1.0,co)",
			"\bwa3_eagle\data\bwa3_eagle_parts_co.paa",
			"\bwa3_backpacks\data\bwa3_backpack_fleck_co.paa",
			"\bwa3_backpacks\data\bwa3_backpack_fleck_co.paa",
			"\bwa3_common\data\bwa3_normteile_co.paa",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)"
		};
	};
};
class cfgMods
{
	author="Reddiem";
	timepacked="1562885989";
};
#endif